version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  default: standard
  enable:
    - misspell
    - goconst
    - dupl
    - revive

linters-settings:
  errcheck:
    check-blank: true
  govet:
    check-shadowing: true
  revive:
    rules:
      - name: exported
        severity: warning
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: var-naming

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - test
    - bin
