version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - misspell
    - goconst
    - dupl
    - revive
  settings:
    errcheck:
      check-blank: false
    revive:
      rules:
        - name: exported
          severity: warning
        - name: error-strings
        - name: error-naming
        - name: if-return
        - name: var-naming

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
