version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - misspell
    - goconst
    - dupl
    - revive
  settings:
    errcheck:
      check-blank: false
    revive:
      rules:
        - name: exported
          severity: warning
        - name: error-strings
        - name: error-naming
        - name: if-return
        - name: var-naming
  exclusions:
    rules:
      # Exclude goconst, dupl, and revive from test files
      - path: _test\.go
        linters:
          - goconst
          - dupl
          - revive
      # Exclude from test/ directory
      - path: test/
        linters:
          - goconst
          - dupl
          - revive

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
