#!/bin/bash

# Telos Idea Matrix Installation & Alias Setup Script
# This script builds and installs the binary and sets up aliases

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}🔧 Installing Telos Idea Matrix and setting up aliases...${NC}"

# Get the project directory
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo -e "${BLUE}📁 Project directory: $PROJECT_DIR${NC}"

# Detect shell
if [[ "$SHELL" == *"zsh"* ]]; then
    SHELL_TYPE="zsh"
    RC_FILE="$HOME/.zshrc"
elif [[ "$SHELL" == *"bash"* ]]; then
    SHELL_TYPE="bash"
    RC_FILE="$HOME/.bashrc"
else
    SHELL_TYPE="unknown"
    RC_FILE="$HOME/.bashrc"  # Default to bash
fi

echo -e "${BLUE}🐚 Detected shell: $SHELL_TYPE${NC}"

# Create local bin directory if it doesn't exist
LOCAL_BIN="$HOME/.local/bin"
mkdir -p "$LOCAL_BIN"
echo -e "${GREEN}✅ Created local bin directory: $LOCAL_BIN${NC}"

# Build the release binary
echo -e "${BLUE}🔨 Building release binary...${NC}"
cd "$PROJECT_DIR"
./make.sh -r  # Use our enhanced make script to build release

# Check if the binary was created
BINARY_PATH="$PROJECT_DIR/bin/tm"
if [ -f "$BINARY_PATH" ]; then
    # Copy binary to local bin (only if different or doesn't exist)
    if [ ! -f "$LOCAL_BIN/tm" ] || ! cmp -s "$BINARY_PATH" "$LOCAL_BIN/tm"; then
        cp "$BINARY_PATH" "$LOCAL_BIN/tm"
        chmod +x "$LOCAL_BIN/tm"
        echo -e "${GREEN}✅ Binary installed to $LOCAL_BIN/tm${NC}"
    else
        echo -e "${YELLOW}⚠️  Binary already exists and is up to date${NC}"
    fi

    # Verify the binary works
    if "$LOCAL_BIN/tm" --help >/dev/null 2>&1; then
        echo -e "${GREEN}✅ Binary works correctly${NC}"
    else
        echo -e "${RED}❌ Binary doesn't work as expected${NC}"
    fi
else
    echo -e "${RED}❌ Could not find built binary at $BINARY_PATH${NC}"
    echo -e "${YELLOW}Trying go build...${NC}"
    mkdir -p "$PROJECT_DIR/bin"
    go build -o "$BINARY_PATH" ./cmd/cli
    if [ -f "$BINARY_PATH" ]; then
        cp "$BINARY_PATH" "$LOCAL_BIN/tm"
        chmod +x "$LOCAL_BIN/tm"
        echo -e "${GREEN}✅ Binary installed to $LOCAL_BIN/tm${NC}"
    else
        echo -e "${RED}❌ Failed to build binary${NC}"
        exit 1
    fi
fi

# Check if $LOCAL_BIN is in PATH
if [[ ":$PATH:" != *":$LOCAL_BIN:"* ]]; then
    echo -e "${YELLOW}⚠️  $LOCAL_BIN is not in your PATH${NC}"
    
    # Add to shell configuration
    if ! grep -q "$LOCAL_BIN" "$RC_FILE" 2>/dev/null; then
        {
            echo "";
            echo "# Add local binaries to PATH";
            echo "export PATH=\"\$PATH:$LOCAL_BIN\"";
            echo "";
        } >> "$RC_FILE"
        
        echo -e "${GREEN}✅ Added $LOCAL_BIN to PATH in $RC_FILE${NC}"
    fi
    
    # Also add to .bash_profile for macOS terminal compatibility
    if [ "$SHELL_TYPE" = "zsh" ]; then
        if [ -f "$HOME/.bash_profile" ] && ! grep -q "$LOCAL_BIN" "$HOME/.bash_profile" 2>/dev/null; then
            {
                echo "";
                echo "# Add local binaries to PATH";
                echo "export PATH=\"\$PATH:$LOCAL_BIN\"";
                echo "";
            } >> "$HOME/.bash_profile"
        fi
    fi
fi

# Create the alias function
create_alias_function() {
    cat > "$PROJECT_DIR/tm-alias.sh" << EOF
#!/bin/bash

# Automatic alias script for telos-idea-matrix
# Generated by setup-aliases.sh

# Quick dump function - adds idea quickly
tmd() {
    tm dump "\$@"
}

# Quick analyze function
tma() {
    tm analyze "\$@"
}

# Quick review function
tmr() {
    tm review "\$@"
}

# Build the project
tmb() {
    cd "$PROJECT_DIR" && ./make.sh "\$@"
    cd - >/dev/null
}

# Update LLM models
tmm() {
    cd "$PROJECT_DIR" && ./update-llm.sh
    cd - >/dev/null
}

# Start LLM service
tms() {
    cd "$PROJECT_DIR" && ./start-llm.sh
    cd - >/dev/null
}

# Stop LLM service
tmst() {
    cd "$PROJECT_DIR" && ./stop-llm.sh
    cd - >/dev/null
}
EOF
}

# Add aliases to shell configuration
add_to_shell_config() {
    local rc_file="$1"
    local alias_path="$2"
    
    echo -e "${BLUE}📝 Adding aliases to $rc_file${NC}"
    
    # Backup the file first
    if [ -f "$rc_file" ]; then
        cp "$rc_file" "${rc_file}.backup-$(date +%Y%m%d-%H%M%S)"
        echo -e "${GREEN}✅ Backup created: ${rc_file}.backup-*${NC}"
    fi
    
    # Add source line to the file if not already present
    if ! grep -q "source.*tm-alias.sh" "$rc_file" 2>/dev/null; then
        {
            echo "";
            echo "# Telos Idea Matrix aliases";
            echo "source \"$alias_path\"";
            echo "";
        } >> "$rc_file"
        
        echo -e "${GREEN}✅ Aliases added to $rc_file${NC}"
    else
        echo -e "${YELLOW}⚠️  Aliases already present in $rc_file${NC}"
    fi
}

# Main function
main() {
    echo -e "${BLUE}📋 Step 1: Creating alias function script${NC}"
    create_alias_function
    
    # Make the alias script executable
    chmod +x "$PROJECT_DIR/tm-alias.sh"
    echo -e "${GREEN}✅ Alias script created and made executable${NC}"
    
    echo -e "${BLUE}📋 Step 2: Adding aliases to shell configuration${NC}"
    add_to_shell_config "$RC_FILE" "$PROJECT_DIR/tm-alias.sh"
    
    # Also add to .bashrc if using zsh (for compatibility)
    if [ "$SHELL_TYPE" = "zsh" ]; then
        if [ -f "$HOME/.bashrc" ] && ! grep -q "source.*tm-alias.sh" "$HOME/.bashrc" 2>/dev/null; then
            add_to_shell_config "$HOME/.bashrc" "$PROJECT_DIR/tm-alias.sh"
        fi
    fi
    
    echo -e "${BLUE}📋 Step 3: Creating installation message${NC}"
    echo "";
    echo -e "${GREEN}🎉 Telos Idea Matrix installed successfully!${NC}"
    echo "";
    echo -e "${BLUE}Available commands:${NC}"
    echo -e "  ${GREEN}tm${NC}          - Run telos-idea-matrix from anywhere"
    echo -e "  ${GREEN}tmd${NC}         - Quick dump an idea: tmd \"my idea\""
    echo -e "  ${GREEN}tma${NC}         - Analyze an idea from anywhere"
    echo -e "  ${GREEN}tmr${NC}         - Review ideas from anywhere" 
    echo -e "  ${GREEN}tmb${NC}         - Build the project: tmb -d (dev), tmb -r (release)"
    echo -e "  ${GREEN}tms${NC}         - Start LLM service"
    echo -e "  ${GREEN}tmst${NC}        - Stop LLM service"
    echo -e "  ${GREEN}tmm${NC}         - Update LLM models"
    echo "";
    echo -e "${BLUE}💡 To use now:${NC}"
    echo -e "  Run: ${GREEN}source $PROJECT_DIR/tm-alias.sh${NC}"
    echo -e "  Or restart your terminal, or run: ${GREEN}source $RC_FILE${NC}"
    echo -e "  Then test with: ${GREEN}tm --help${NC}"
    echo "";
    echo -e "${BLUE}📝 The binary and aliases will be available in new terminal sessions${NC}"
}

# Run main function
main "$@"