#!/bin/bash

# Automatic alias script for telos-idea-matrix
# Generated by setup-aliases.sh

# Quick dump function - adds idea quickly
tmd() {
    tm dump "$@"
}

# Quick analyze function
tma() {
    tm analyze "$@"
}

# Quick review function
tmr() {
    tm review "$@"
}

# Build the project
tmb() {
    cd "/Users/rayyacub/Documents/CCResearch/telos-idea-matrix" && ./make.sh "$@"
    cd - >/dev/null
}

# Update LLM models
tmm() {
    cd "/Users/rayyacub/Documents/CCResearch/telos-idea-matrix" && ./update-llm.sh
    cd - >/dev/null
}

# Start LLM service
tms() {
    cd "/Users/rayyacub/Documents/CCResearch/telos-idea-matrix" && ./start-llm.sh
    cd - >/dev/null
}

# Stop LLM service
tmst() {
    cd "/Users/rayyacub/Documents/CCResearch/telos-idea-matrix" && ./stop-llm.sh
    cd - >/dev/null
}