openapi: 3.0.3
info:
  title: Telos Idea Matrix API
  description: RESTful API for analyzing and managing ideas based on personal telos (goals, strategies, and anti-patterns)
  version: 1.0.0
  contact:
    name: API Support
    url: https://github.com/rayyacub/telos-idea-matrix

servers:
  - url: http://localhost:8080
    description: Local development server
  - url: http://localhost:8080/api/v1
    description: API v1 base path

tags:
  - name: health
    description: Health check endpoints
  - name: ideas
    description: Idea management operations
  - name: analysis
    description: Idea analysis operations
  - name: analytics
    description: Analytics and statistics

paths:
  /health:
    get:
      tags:
        - health
      summary: Health check
      description: Returns the health status of the API
      operationId: healthCheck
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok

  /api/v1/analyze:
    post:
      tags:
        - analysis
      summary: Analyze an idea
      description: Analyzes an idea against the user's telos without saving it
      operationId: analyzeIdea
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  description: The idea content to analyze
                  example: Build an AI-powered Go code reviewer that ships in 2 weeks
      responses:
        '200':
          description: Analysis completed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalyzeResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/ideas:
    get:
      tags:
        - ideas
      summary: List ideas
      description: Returns a paginated list of ideas with optional filtering
      operationId: listIdeas
      parameters:
        - name: status
          in: query
          description: Filter by status
          schema:
            type: string
            enum: [active, archived, deleted]
        - name: limit
          in: query
          description: Maximum number of results
          schema:
            type: integer
            default: 100
        - name: offset
          in: query
          description: Offset for pagination
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of ideas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListIdeasResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      tags:
        - ideas
      summary: Create idea
      description: Creates a new idea with automatic analysis
      operationId: createIdea
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  description: The idea content
                  example: Build an AI-powered Go code reviewer
      responses:
        '201':
          description: Idea created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdeaResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/ideas/{id}:
    get:
      tags:
        - ideas
      summary: Get idea by ID
      description: Returns a single idea by its ID
      operationId: getIdea
      parameters:
        - name: id
          in: path
          required: true
          description: Idea ID (UUID)
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Idea found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdeaResponse'
        '400':
          description: Invalid ID format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Idea not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      tags:
        - ideas
      summary: Update idea
      description: Updates an existing idea (re-analyzes if content changes)
      operationId: updateIdea
      parameters:
        - name: id
          in: path
          required: true
          description: Idea ID (UUID)
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  description: Updated idea content
                status:
                  type: string
                  enum: [active, archived, deleted]
                  description: Updated status
      responses:
        '200':
          description: Idea updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdeaResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Idea not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      tags:
        - ideas
      summary: Delete idea
      description: Deletes an idea by ID
      operationId: deleteIdea
      parameters:
        - name: id
          in: path
          required: true
          description: Idea ID (UUID)
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Idea deleted successfully
        '400':
          description: Invalid ID format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Idea not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/analytics/stats:
    get:
      tags:
        - analytics
      summary: Get statistics
      description: Returns analytics and statistics about all ideas
      operationId: getStats
      responses:
        '200':
          description: Statistics retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatsResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    IdeaResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier
        content:
          type: string
          description: Idea content
        raw_score:
          type: number
          format: float
          description: Raw score before adjustments
        final_score:
          type: number
          format: float
          description: Final adjusted score (0-10)
        patterns:
          type: array
          items:
            type: string
          description: Detected anti-patterns
        recommendation:
          type: string
          description: Recommendation based on score
          enum:
            - 🔥 PRIORITIZE NOW
            - ✅ GOOD ALIGNMENT
            - ⚠️ CONSIDER LATER
            - 🚫 AVOID FOR NOW
        analysis:
          $ref: '#/components/schemas/Analysis'
        created_at:
          type: string
          format: date-time
          description: Creation timestamp (RFC3339)
        reviewed_at:
          type: string
          format: date-time
          description: Review timestamp (RFC3339)
          nullable: true
        status:
          type: string
          enum: [active, archived, deleted]
          description: Idea status

    Analysis:
      type: object
      properties:
        raw_score:
          type: number
          format: float
        final_score:
          type: number
          format: float
        mission:
          $ref: '#/components/schemas/MissionScores'
        anti_challenge:
          $ref: '#/components/schemas/AntiChallengeScores'
        strategic:
          $ref: '#/components/schemas/StrategicScores'
        detected_patterns:
          type: array
          items:
            $ref: '#/components/schemas/DetectedPattern'
        recommendations:
          type: array
          items:
            type: string
        scoring_details:
          type: array
          items:
            type: string
        explanations:
          type: object
          additionalProperties:
            type: string
        analyzed_at:
          type: string
          format: date-time

    MissionScores:
      type: object
      description: Mission alignment scores (max 4.0 points, 40%)
      properties:
        domain_expertise:
          type: number
          format: float
          description: Domain expertise score (0-1.2)
        ai_alignment:
          type: number
          format: float
          description: AI alignment score (0-1.5)
        execution_support:
          type: number
          format: float
          description: Execution support score (0-0.8)
        revenue_potential:
          type: number
          format: float
          description: Revenue potential score (0-0.5)
        total:
          type: number
          format: float
          description: Total mission score (max 4.0)

    AntiChallengeScores:
      type: object
      description: Anti-challenge scores (max 3.5 points, 35%)
      properties:
        context_switching:
          type: number
          format: float
          description: Context switching avoidance (0-1.2)
        rapid_prototyping:
          type: number
          format: float
          description: Rapid prototyping support (0-1.0)
        accountability:
          type: number
          format: float
          description: Accountability mechanisms (0-0.8)
        income_anxiety:
          type: number
          format: float
          description: Income anxiety mitigation (0-0.5)
        total:
          type: number
          format: float
          description: Total anti-challenge score (max 3.5)

    StrategicScores:
      type: object
      description: Strategic fit scores (max 2.5 points, 25%)
      properties:
        stack_compatibility:
          type: number
          format: float
          description: Stack compatibility (0-1.0)
        shipping_habit:
          type: number
          format: float
          description: Shipping habit support (0-0.8)
        public_accountability:
          type: number
          format: float
          description: Public accountability (0-0.4)
        revenue_testing:
          type: number
          format: float
          description: Revenue testing potential (0-0.3)
        total:
          type: number
          format: float
          description: Total strategic score (max 2.5)

    DetectedPattern:
      type: object
      properties:
        name:
          type: string
          description: Pattern name
        description:
          type: string
          description: Pattern description
        confidence:
          type: number
          format: float
          description: Confidence level (0.0-1.0)
        severity:
          type: string
          enum: [low, medium, high, critical]
          description: Pattern severity

    AnalyzeResponse:
      type: object
      properties:
        analysis:
          $ref: '#/components/schemas/Analysis'

    ListIdeasResponse:
      type: object
      properties:
        ideas:
          type: array
          items:
            $ref: '#/components/schemas/IdeaResponse'
        total:
          type: integer
          description: Total number of results
        limit:
          type: integer
          description: Result limit
        offset:
          type: integer
          description: Result offset

    StatsResponse:
      type: object
      properties:
        total_ideas:
          type: integer
          description: Total number of ideas
        active_ideas:
          type: integer
          description: Number of active ideas
        average_score:
          type: number
          format: float
          description: Average score across all ideas
        high_score:
          type: number
          format: float
          description: Highest score
        low_score:
          type: number
          format: float
          description: Lowest score

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
